app/models.py
from app import db
from datetime import datetime
import re
from flask_security import UserMixin,RoleMixin


def slugify(s):
	pattern = r'[^\w+]'
	return re.sub(pattern,'-',s)
post_tags = db.Table('post_tags',
					 db.Column('post_id',db.Integer,db.ForeignKey('post.id')),
					 db.Column('tag_id',db.Integer, db.ForeignKey('tag.id'))
					 ) 
#db - экземпляр класса SQLAlchemy 
#'post_tags' - навание таблцы в базе 

class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(140))
	slug = db.Column(db.String(140),unique=True)
	body = db.Column(db.Text)
	created = db.Column(db.DateTime,default = datetime.now())

	def __init__(self, *args, **kwargs):
	    super(Post, self).__init__(*args, **kwargs)
	    self.generate_slug()

	def generate_slug(self):
		if self.title:
			self.slug = slugify(self.title)
	
	def __repr__(self):
		return '<Post id: {}, title: {}>'.format(self.id,self.title)

	tags = db.relationship('Tag', secondary=post_tags, backref = db.backref('posts', lazy = 'dynamic'))


class Tag(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(100))
	slug = db.Column(db.String(100))

	def __init__(self, *args, **kwargs):
	    super(Tag, self).__init__(*args, **kwargs)
	    self.slug = slugify(self.name)
	def __repr__(self):
		return '{}'.format(self.name)

### flask_security

rolse_users = db.Table('rols_users',
					   db.Column('user_id', db.Integer(),db.ForeignKey('user.id')),
					   db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))


class User(db.Model,UserMixin):
	id = db.Column(db.Integer(),primary_key=True)
	email = db.Column(db.String(100),unique=True)
	password = db.Column(db.String(255))
	active = db.Column(db.Boolean())
	roles = db.relationship('Role',secondary=rolse_users, backref = db.backref('users', lazy='dynamic') )

class Role(db.Model,RoleMixin):
	id = db.Column(db.Integer(),primary_key=True)
	name = db.Column(db.String(255),unique=True)
	description = db.Column(db.String(255))

app/posts/forms.py
from wtforms import Form,StringField,TextAreaField

class PostForm(Form):
	title = StringField('Title')
	body = TextAreaField('Body')











#они выстраивают соответвие между моделями и html формами

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate,MigrateCommand 
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user
from flask import redirect,url_for,request
from flask_admin import AdminIndexView
app = Flask(__name__)

app.config.from_object(Configuration)


db = SQLAlchemy(app)


migrate = Migrate(app,db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

### ADMIN ###
from models import *

class AdminMixin:
	def is_accessible(self):
		return current_user.has_role('admin')

	def inaccessible_callback(self,name,**kwargs):
		return redirect(url_for('security.login', next=request.url))

class BaseModelView(ModelView):
	def on_model_change(self,form,model,is_created):
		model.generate_slug()
		return super(BaseModelView,self).on_model_change(form,model,is_created)
class PostAdminView(AdminMixin,BaseModelView):
	form_columns = ['title','body','tags']
class TagAdminView(AdminMixin,BaseModelView):
	form_columns =  ['name','posts']

class AdminView(AdminMixin,ModelView):
	pass	
class HomeAdminView(AdminMixin,AdminIndexView):
	pass
		
admin = Admin(app,'FlaskApp',url='',index_view =HomeAdminView(name ='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))




### flask_security

user_datastore = SQLAlchemyUserDatastore(db,User,Role)
security = Security(app,user_datastore )

app/main.py
from app import app
from config import Configuration
import view
from app import db 
from posts.blueprint import posts
from map.blueprint import maps

app.register_blueprint(maps,url_prefix = '/maps')
app.register_blueprint(posts, url_prefix = '/blog')


	







if __name__ == '__main__':
	app.run()

app/map/blueprint.py
from flask import Blueprint,render_template,request,flash,redirect,url_for,session
import dash
import dash_core_components as dcc
import dash_html_components as html
maps = Blueprint('maps',__name__,template_folder = 'templates',static_folder = 'static',static_url_path='/static/')


@maps.route('/loginn', methods=['POST','GET'])
def loginn():
	if request.method == 'POST':
		print(session)
	return render_template('login.html',username=['userLogget'])
@maps.route('/form',methods = ['POST','GET'])
def form():
	if request.method == 'POST':
		try:
			if len(request.form['q']) > 2:
				flash('Строка больше двух',category = 'success')
			else:
				flash('Меньше ёп')	
			
			print(request.form['q'])
		except:
			pass
		return render_template('maps/form.html')
@maps.route('/form')
def form2():
	if request.method == 'POST':
		flash('sdfsdf')



	return render_template('maps/form.html',alert)
@maps.route('/conspect')
def conspect():
	return render_template('maps/conspect.html')


@maps.route('/')
def index():
	return render_template('maps/index.html')

    
if __name__ == '__main__':
    app.run_server(debug=True)

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post,Tag
from flask import request
from .forms import PostForm
from app import db
from flask import redirect
from flask import url_for
from flask_security import login_required
posts = Blueprint('posts',__name__, template_folder = 'templates')


#http://localhost/blog/create
@posts.route('/create',methods=['POST','GET'] )
@login_required
def create_post():

	form = PostForm()
	if request.method == 'POST':
		title = request.form['title']
		body = request.form['body']

		try:
			post = Post(title = title, body = body)
			db.session.add(post)
			db.session.commit()
		except:
			print('Somthing wrong')

		return redirect(url_for('posts.index'))

	return render_template('posts/create_post.html',form=form)


@posts.route('/<slug>/edit/',methods = ['POST', 'GET'])
@login_required
def edit_post(slug):
	post = Post.query.filter(Post.slug==slug).first()
	if request.method == 'POST':
		form = PostForm(formdata=request.form,obj=post)
		form.populate_obj(post)
		db.session.commit()
		return redirect(url_for('posts.post_detail', slug = post.slug))
	form = PostForm(obj=post)
	return render_template('posts/edit_post.html',post=post, form = form)




@posts.route('/')
def index():
	q = request.args.get('q') 
	page = request.args.get('page')
	if page and page.isdigit():
		page = int(page)
	else:
		page = 1 

	if q:
		posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
	else:
		posts = Post.query.order_by(Post.created.desc())
	pages = posts.paginate(page=page,per_page=5)	

	return render_template('posts/index.html',posts=posts,pages=pages)
#http://localhost/blog/first-post
@posts.route('/<slug>') # угловые скобки - имя параметра first-post транслируется в <slug>
def post_detail(slug):
	post = Post.query.filter(Post.slug == slug).first()
	tags = post.tags
	
	return render_template('posts/post_detail.html', post=post,tags = tags)
# http://localhost/blog/tag/python
@posts.route('/tag/<slug>')
def tag_detail(slug):
	tag = Tag.query.filter(Tag.slug == slug).first()
	posts = tag.posts.all()
	return render_template('posts/tag_detail.html', tag= tag,posts = posts)

app/map/templates/maps/conspect.html
{% extends "base.html" %}

{% block title %}
selfedu7
{% endblock title %}

{% block content %}

{{super()}}
<link href="{{ url_for('static', filename='css/rainbow.css') }}" rel="stylesheet" >
<link href="{{ url_for('static', filename='css/css.css') }}" rel="stylesheet" >

<div class="d-flex flex-nowrap bd-highlight">
  <div class="order-3 p-2 bd-highlight">
  	<p>Декоратор errorhandler - нужен для отлова ошибок. Пишем следующий код во файле view.py</p>
  </div>
 
 <div class="order-1 p-2 bd-highlight "><p><pre><code data-language="python">
@app.errorhandler(404)
def pageNotFount(error):
	return render_template('page404.html')
		</code></pre></p>
	</div>
</div>
<div class="d-flex flex-nowrap bd-highlight">
  <div class="order-3 p-2 bd-highlight">
  	<p>Функция Flash() нужна для вывода алертов с мнговенной информации</p>
  </div>
 
 <div class="order-1 p-2 bd-highlight "><p><pre><code data-language="python">
@maps.route('/form',methods = ['POST','GET'])
def form():
	if request.method == 'POST':
		if len(request.form['q']) > 2:
			flash('Строка больше двух',category = 'success')
		else:
			flash('Меньше ёп')	
		
		print(request.form['q'])
	return render_template('maps/form.html')
		</code></pre></p>
	</div>
</div>


<script src="{{url_for('static', filename='js/rainbow-custom.min.js')}}"></script>



{% endblock content %}

app/map/templates/maps/form.html
{% extends "base.html" %}

{% block content %}

 {% for cat,m in  get_flashed_messages(True) %}
{% if cat=='success' %}
      <div class="alert alert-primary" role="alert">{{m}}{{cat}}</div>
{% else %}
      <div class="alert alert-danger" role="alert">{{m}}</div>
{% endif %}
   


 {% endfor %}
<div class="col-md-6">
<form method = 'POST' action="{{ url_for('maps.form') }}">
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <input type="text" class='form-control' name ='q'> 
   
  <button type="submit" class="btn btn-primary">Submit</button>

</form>
</div>

<div class="col-md-6">
<form method = 'POST' action="{{ url_for('maps.form2') }}">
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <input type="text" class='form-control' name ='alert'> 
   
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>
<h1>{{get_flashed_messages()}}</h1>

{% endblock content %}

app/map/templates/maps/index.html
{% extends "base.html" %}
{% block title %}
	Maps
{% endblock title %}





{% block content %}
	<p><a href="{{url_for('maps.form')}}">Form</a></p>
	<p><a href="{{ url_for('maps.conspect') }}">Конспект</a></p>
{% endblock content %}

app/map/templates/maps/profile.html
{% extends "base.html" %}

{% block contant %}
	welcome {{username}}
{% endblock contant %}

app/posts/templates/posts/create_post.html
{%extends 'base.html'%}

{% block title %}
New Post
{% endblock title %}

{% block content_title %}
<p>New post</p>
{% endblock%}

{% block content %}
<div class="col-md-6">
	<form action="{{ url_for('posts.create_post') }}" method="POST">
		{% for field in form %}

		<div class="form-group">
			{{field.label(class='control-label')}}
			{{field(class ='form-control')}}
		</div>


		{% endfor %}
		<button type="submit" class="btn btn-outline-primary">Create</button>		
	</form>
</div>
{% endblock%}

app/posts/templates/posts/edit_post.html
{%extends 'base.html'%}

{% block title %}
 Edit post
{% endblock title %}

{% block content_title %}
<p>Edit post</p>
{% endblock%}

{% block content %}
<div class="col-md-6">
	<form action="{{ url_for('posts.edit_post',slug=post.slug)}}" method="POST">
		{% for field in form %}

		<div class="form-group">
			{{field.label(class='control-label')}}
			{{field(class ='form-control')}}
		</div>


		{% endfor %}
		<button type="submit" class="btn btn-outline-primary">Edit</button>		
	</form>
</div>
{% endblock%}

app/posts/templates/posts/index.html
{%extends 'base.html'%}

{%block title%}

Posts

{%endblock%}


{%block content_title%}
Blueprint index page
{%endblock%}


{%block content%}

{%for post in pages.items%}
<div class="card" style="width: 18rem;margin-bottom:20px;">
	<div class="card-body bg-light">
		<h5 class="card-title  text-dark">{{post.title}}</h5>
		<p class="card-text text-dark">{{post.body}}</p>
		<a href="{{url_for('posts.post_detail',slug=post.slug)}}" class="btn btn-secondary">Read more</a>
		{# <h6>Tags:<span class="badge dge-secondary">{{tags}}</span></h6> #}
	</div>
</div>
{%endfor%} 



<nav>
	<ul class="pagination justify-content-center">
		<li {% if not pages.has_prev %} class='page-item disabled' {% endif %} > 
			<a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1"><</a>
		</li>
		{% for page in pages.iter_pages()  %}
			<li {% if page == pages.page %} class="page-item active bg-secondary" {%endif%}>
				<a class="page-link " href="./?page={{ page }}">{{ page  }}</a>
			
			
			</li>
			
		{% endfor %}
		<li {% if not pages.has_next%}class="page-item disabled"{%endif%}>
			<a class="page-link" href="./?page={{ pages.next_num }}">></a>
		</li>
	</ul>
</nav>
{%endblock%}

app/posts/templates/posts/post_detail.html
{%extends 'base.html'%}

{%block title%}

	{{post.title}}

{%endblock%}


{%block content_title%}
	{{post.title}}
{%endblock%}


{%block content%}
	{{post.body}}
	<div class= 'tags'>
		{%for tag in tags %}
			<a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}"><span class="badge badge-primary">{{ tag.name }}</span></a>

			
		{%endfor%}
		<a href="{{ url_for('posts.edit_post',slug=post.slug) }}"><button type="buttom" class="btn btn-outline-primary">Edit</button></a>
	</div>

{%endblock%}

app/posts/templates/posts/tag_detail.html
{%extends 'base.html'%}

{%block title%}

	{{tag.name}} | posts

{%endblock%}


{%block content_title%}
	Posts for "{{tag.name}}" tag
{%endblock%}

	


{%block content%}
	{% for post in posts %}
		<div class="card" style="width: 18rem;margin-bottom:20px;">
		<div class="card-body">
			<h5 class="card-title">{{post.title}}</h5>
			<p class="card-text">{{post.body}}</p>
			<a href="{{url_for('posts.post_detail',slug=post.slug)}}" class="btn btn-primary">Read more</a>
			<h6>Tags:<span class="badge badge-secondary">{{tags}}</span></h6>
		</div>
		
		
	{% endfor %}

{%endblock%}

app/templates/about.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

	<title>Hello, world!</title>
</head>
<body>
	<head>
		<ul class="nav justify-content-center">
			<li class="nav-item">
				<a class="nav-link active" href="#">Active</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
			</li>
		</ul>
	</head>
	<h1>Hello, world!</h1>
	<div class="dropdown">
		<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Dropdown button
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<a class="dropdown-item" href="#">Action</a>
			<a class="dropdown-item" href="#">Another action</a>
			<a class="dropdown-item" href="#">Something else here</a>
		</div>
	</div>
	<!-- Optional JavaScript; choose one of the two! -->

	<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

	<title>
		{%block title%}
		{%endblock%} | Flask App
	</title>
</head>
<body class = ' bg-dark text-white' >
	<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
			<a class="nav-link active" href="{{ url_for('index') }}">Home</a>
			<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('posts.index')}}">Blog</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('maps.index') }}">Map</a>
				</li>
				<li class="nav-item">
					{# <a class="nav-link" href="{{ url_for('posts.create_post') }}">Create post</a> #}
					<li>
						{%if current_user.has_role('admin')%}
						<a class="nav-link" href="/admin">Admin</a>
						{%endif%}
					</li>
				</li>
			</ul>
			<form class="form-inline my-2 my-lg-0" method="GET">
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='q' value='{{ request.args.get('q','') }}'>
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
		</div>
	</nav>
	<div class="container">
		<div class="row">
			<h1>
				{%block content_title%}

				{%endblock%}
			</h1>

		</div>
		{%block content%}

		{%endblock%}
	</div>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>

app/templates/contactus.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

	<title>Hello, world!</title>
</head>
<body>
	<head>
		<ul class="nav justify-content-center">
			<li class="nav-item">
				<a class="nav-link active" href="#">Active</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
			</li>
		</ul>
	</head>
	<h1>Hello, world!</h1>
	<div class="dropdown">
		<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Dropdown button
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<a class="dropdown-item" href="#">Action</a>
			<a class="dropdown-item" href="#">Another action</a>
			<a class="dropdown-item" href="#">Something else here</a>
		</div>
	</div>
	<!-- Optional JavaScript; choose one of the two! -->

	<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>

app/templates/index.html
{%extends 'base.html'%}
{%block title%}
pop
{%endblock%}



{%block content_title%}
content_title
{%endblock%}
{%block content%}

	Content

{%endblock%}

app/templates/login.html
{% extends "base.html" %}
{% block title %}
	your profile
{% endblock title %}
{% block content_title %}
	
{% endblock content_title %}
{% block content %}
	<form action="{{ url_for('maps.loginn') }}" method='POST'>
  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name = 'username'>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name ='psw'>
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

app/templates/page404.html
{% extends "base.html" %}
{% block title %}
	страницы не найдена
{% endblock title %}
{% block content_title %}
	Страницы не нейдена 404
{% endblock content_title %}

app/templates/profile.html
{% extends "base.html" %}

{% block contant %}
	welcome {{username}}
{% endblock contant %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

app/templates/security/login_user.html
{%extends 'base.html'%}

{% block title %}
	Login
{% endblock title %}
{% block content_title  %}
<h1>{{ _('Login') }}</h1>
{% endblock%}

{% block content %}
	
{% from "security/_macros.html" import render_field_with_errors, render_field %}
<div class="col-md-3 offset-md-3 col-md-6">
{% include "security/_messages.html" %}
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email,class = 'form-control') }}
  {{ render_field_with_errors(login_user_form.password,class = 'form-control') }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit,class="btn btn-outline-primary") }}
</form>
{% include "security/_menu.html" %}
</div>
{% endblock content %}

app/templates/sudebar.html
<ul class="nav justify-content-center">
			<li class="nav-item">
				<a class="nav-link active" href="#">Active</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
			</li>
		</ul>